Acme\StoreBundle\Entity\Category:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: category
